src/core/urls.py
from django.urls import path

from core.views import IndexView

app_name = "core"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
]

src/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("__debug__/", include("debug_toolbar.urls")),
        path("admin/", admin.site.urls),
        path("accounts/", include("allauth.urls")),
        path("", include("core.urls")),
        path("users/", include("users.urls")),
        path("exchange/", include("exchange.urls")),
        path("services/", include("services.urls")),
        path("projects/", include("projects.urls")),
        path("orders/", include("orders.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)


# Configure Admin panel titles
admin.site.site_header = "Биржа Услуг – Администрирование"
admin.site.site_title = "Биржа Услуг – Админка"
admin.site.index_title = "Биржа Услуг – Админка"

src/orders/urls.py
from django.urls import path

from orders.views import (
    OrderDetailView,
    OrderListView,
    order_service_create_view,
    order_set_status_view,
)

app_name = "orders"
urlpatterns = [
    path("", OrderListView.as_view(), name="list"),
    path("<int:pk>/", OrderDetailView.as_view(), name="detail"),
    path("create/service/", order_service_create_view, name="create_service"),
    path("set_status/<int:order_id>/", order_set_status_view, name="set_status"),
]

src/projects/urls.py
from django.urls import path

from projects.views import (
    ProjectCreateView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectListView,
    ProjectMyListView,
    ProjectUpdateView,
    offer_create_view,
    offer_set_status_view,
)

app_name = "projects"
urlpatterns = [
    path("", ProjectListView.as_view(), name="list"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="detail"),
    path("my/", ProjectMyListView.as_view(), name="my_list"),
    path("create/", ProjectCreateView.as_view(), name="create"),
    path("update/<int:pk>/", ProjectUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", ProjectDeleteView.as_view(), name="delete"),
    path("offer/create/", offer_create_view, name="offer_create"),
    path(
        "offer/set_status/<int:offer_id>/",
        offer_set_status_view,
        name="offer_set_status",
    ),
]

src/users/urls.py
from django.urls import path

from users.views import (
    UserPublicProfileView,
    UserUpdateBalanceView,
    UserUpdateProfileView,
    OnboardingQuestionnaireView,
)
from users.views_recommendations import UserRecommendationsView

app_name = "users"
urlpatterns = [
    path("update/<int:pk>/", UserUpdateProfileView.as_view(), name="update"),
    path("balance/", UserUpdateBalanceView.as_view(), name="update_balance"),
    path("onboarding/", OnboardingQuestionnaireView.as_view(), name="onboarding"),
    path("recommendations/", UserRecommendationsView.as_view(), name="recommendations"),
    path("<str:username>/", UserPublicProfileView.as_view(), name="public_profile"),
]

src/projects/models.py
from django.db import models
from exchange.models import Category
from users.models import CustomUser


class Project(models.Model):
    """Проект, предлагаемый пользователем для реализации другими пользователями."""

    customer = models.ForeignKey(
        verbose_name="замовник проєкту",
        help_text="Користувач, який пропонує даний проєкт для реалізації",
        to=CustomUser,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        related_name="projects",
    )
    title = models.CharField(
        verbose_name="назва",
        max_length=70,
        null=False,
        blank=False,
    )
    category = models.ForeignKey(
        verbose_name="рубрика",
        help_text="Категорія, в якій буде розміщено проєкт",
        to=Category,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        related_name="projects",
    )
    description = models.TextField(
        verbose_name="детальний опис завдання",
        help_text="Опишіть, що саме вам потрібно, в якому обсязі і за який термін.",
        max_length=5200,
        null=False,
        blank=False,
    )
    price = models.IntegerField(
        verbose_name="ціна не більше",
        help_text="Ваш бюджет в грн.",
        null=False,
        blank=False,
    )
    is_higher_price_allowed = models.BooleanField(
        verbose_name="Готовий розглянути пропозиції з ціною вище, якщо рівень виконавця буде вищим",
        default=False,
    )
    max_price = models.IntegerField(
        verbose_name="максимальна ціна",
        help_text="Максимальна ціна у разі високого рівня виконавця.",
        null=True,
        blank=True,
    )
    is_active = models.BooleanField(
        verbose_name="проєкт активний",
        help_text="Зніміть галочку, щоб виключити проєкт з каталогу, не видаляючи його.",
        default=True,
    )
    created = models.DateTimeField(
        verbose_name="створено",
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        verbose_name="змінено",
        auto_now=True,
    )

    class Meta:
        ordering = ["-created"]
        verbose_name = "проєкт"
        verbose_name_plural = "проєкти"

    def __str__(self):
        return self.title


class Offer(models.Model):
    """Предложение кандидатом своей послуги по выполнению проєкта замовника."""

    STATUS_CHOICES = (
        ("created", "Створено кандидатом"),
        ("declined", "Відхилено замовником"),
        ("cancelled", "Скасовано кандидатом"),
        ("accepted", "Прийнято замовником"),
    )

    project = models.ForeignKey(
        verbose_name="проєкт",
        to=Project,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        related_name="offers",
    )
    candidate = models.ForeignKey(
        verbose_name="кандидат на выполнение проєкта",
        help_text="Пользователь, который предлагает свои послуги для реализации проєкта.",
        to=CustomUser,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        related_name="offers",
    )
    comment = models.TextField(
        verbose_name="комментарий",
        help_text="Коментар кандидата для замовника касательно проєкта.",
        max_length=500,
        null=True,
        blank=True,
    )
    status = models.CharField(
        verbose_name="статус предложения",
        choices=STATUS_CHOICES,
        default="created",
        max_length=32,
    )
    is_cancelled = models.BooleanField(
        verbose_name="скасованоо",
        help_text="Предложение скасованоо или отклонено.",
        default=False,
    )
    created = models.DateTimeField(
        verbose_name="створено",
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        verbose_name="змінено",
        auto_now=True,
    )

    class Meta:
        ordering = ["-created"]
        verbose_name = "предложение"
        verbose_name_plural = "предложения"

src/projects/forms.py
from django import forms


class OfferCreateForm(forms.Form):
    """Невидимая форма створеноия предложения на выполнение проєкта."""

    project_id = forms.IntegerField()


class OfferSetStatusForm(forms.Form):
    """Невидимая форма зміненоия статуса предложения на выполнение проєкта."""

    new_status = forms.CharField()

src/projects/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django_project.rds import redis
from exchange.selectors import (
    category_get_by_id,
    category_list_only_available,
    category_list_only_with_projects,
)
from orders.selectors import order_get_by_project_id
from users.models import Action
from users.services import action_create

from projects.forms import OfferCreateForm, OfferSetStatusForm
from projects.models import Project
from projects.selectors import (
    offer_get_by_id,
    offer_list,
    project_get_by_id,
    project_list,
)
from projects.services import offer_create, offer_set_status


class ProjectListView(ListView):
    model = Project
    template_name = "projects/project_list.html"

    def get_queryset(self):
        category_id = self.request.GET.get("category_id", None)
        search = self.request.GET.get("search", None)
        return project_list(
            category_id=category_id, exclude_with_orders=True, search=search
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        category_id = self.request.GET.get("category_id", None)

        if category_id is not None:
            category = category_get_by_id(category_id)
            context["category"] = category

        context["categories"] = category_list_only_with_projects()
        context["search"] = self.request.GET.get("search", None)
        return context


class ProjectMyListView(LoginRequiredMixin, ListView):
    """Проекты залогиненного пользователя – страница "Мої проєкти"."""

    model = Project
    template_name = "projects/project_my_list.html"

    def get_queryset(self):
        return project_list(customer_id=self.request.user.id)


class ProjectDetailView(DetailView):
    model = Project
    template_name = "projects/project_detail.html"

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)

        if pk is None:
            raise AttributeError(
                "Detail view %s must be called with an object "
                "pk in the URLconf." % self.__class__.__name__
            )

        return project_get_by_id(project_id=pk)

    def get(self, request, *args, **kwargs):
        """
        Для аутентифицированного пользователя создадим действие, чтобы сохранить историю просмотра.
        Перегляды пользователем своих проєктов фиксировать не будем.
        """
        project = self.get_object()
        if project is None:
            raise Http404

        if self.request.user.is_authenticated and (
            project.customer != self.request.user
        ):
            action_create(
                user=self.request.user,
                verb=Action.VIEW_PROJECT,
                target=project,
            )

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        project = self.get_object()

        candidate = None
        if self.request.user.is_authenticated and (
            self.request.user != project.customer
        ):
            candidate = self.request.user

        context["offers"] = offer_list(project_id=project.pk, candidate=candidate)

        user = None
        if self.request.user.is_authenticated:
            user = self.request.user
        context["order"] = order_get_by_project_id(project_id=project.pk, user=user)

        context["total_views"] = redis.incr(f"project:{project.pk}:views")
        return context


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/project_create.html"
    fields = [
        "title",
        "category",
        "description",
        "price",
        "is_higher_price_allowed",
        "max_price",
    ]

    def get_form(self, form_class=None):
        """Оставляем в списке формы только категорії, доступные для назначения услуге."""
        form = super().get_form(form_class)
        form.fields["category"].queryset = category_list_only_available()
        return form

    def form_valid(self, form):
        """Set logged in user as `customer` of new Project."""
        service = form.save(commit=False)
        service.customer = self.request.user
        service.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("projects:detail", kwargs={"pk": self.object.pk})


class ProjectUpdateView(
    LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView
):
    model = Project
    fields = [
        "title",
        "category",
        "is_active",
        "description",
        "price",
        "is_higher_price_allowed",
        "max_price",
    ]
    template_name = "projects/project_update.html"
    success_message = "Сведения о проєкте успешно зміненоы."

    def test_func(self):
        """Only allow user to update own project."""
        user = self.get_object().customer
        return user == self.request.user

    def get_success_url(self):
        return reverse_lazy("projects:update", kwargs={"pk": self.get_object().pk})


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    template_name = "projects/project_delete.html"
    success_url = reverse_lazy("projects:my_list")

    def test_func(self):
        """Only allow owner of the project to delete it."""
        project = self.get_object()
        return project.customer == self.request.user


@require_POST
@login_required
def offer_create_view(request: HttpRequest) -> HttpResponse:
    form = OfferCreateForm(request.POST)

    if form.is_valid():
        data = form.cleaned_data
        project_id = data["project_id"]
        project = project_get_by_id(project_id=project_id)

        if not project:
            raise Http404

        if offer_create(project=project, candidate=request.user):
            messages.success(request, "Вы успешно подали заявку на выполнение проєкта!")
        else:
            messages.warning(
                request,
                "Не удалось разместить вашу заявку на выполнение проєкта.",
                extra_tags="warning",
            )
        return redirect(reverse_lazy("projects:detail", kwargs={"pk": project.pk}))

    return redirect(reverse_lazy("projects:list"))


@require_POST
@login_required
def offer_set_status_view(request: HttpRequest, offer_id: int) -> HttpResponse:
    offer = offer_get_by_id(offer_id)
    if offer is None:
        raise Http404

    if (request.user != offer.candidate) and (request.user != offer.project.customer):
        raise PermissionDenied(
            "Статус предложения могут менять только кандидат или замовник проєкту."
        )

    form = OfferSetStatusForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        new_status = data["new_status"]

        offer_set_status(offer=offer, new_status=new_status, actor=request.user)

        if offer.status == new_status:
            messages.success(request, "Статус предложения успешно изменён.")
        else:
            messages.warning(
                request,
                "Не удалось изменить статус предложения. Попробуйте ещё раз!",
                extra_tags="warning",
            )

    return redirect(reverse_lazy("projects:detail", kwargs={"pk": offer.project.pk}))

src/templates/projects/project_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  Створити новый проєкт
{% endblock %}

{% block content %}
  <section class="mx-auto max-w-5xl">
    <h1 class="text-xl font-semibold mb-2">Створити новый проєкт</h1>

    <form action="{% url 'projects:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {{ form|crispy }}

      <button type="submit" class="inline-flex items-center px-5 py-2.5 mt-4 text-sm font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:bg-blue-800">
        Створити проєкт
      </button>
    </form>
  </section>
{% endblock content %}

src/templates/projects/project_delete.html
{% extends "base.html" %}

{% block title %}
  Видалити проєкт
{% endblock %}

{% block content %}
  <section class="mx-auto max-w-5xl">
    <h1 class="text-xl font-semibold mb-2">Видалити проєкт</h1>

    <div class="mb-4 p-4">
      <form action="" method="post">
        {% csrf_token %}

        <p class="text-red-500">
          Вы уверены, что хотите удалить проєкт &laquo;{{ project.title }}&raquo;?
        </p>

        <button type="submit" class="inline-flex items-center px-5 py-2.5 mt-4 text-sm font-medium text-center text-white bg-red-700 rounded-lg focus:ring-4 focus:ring-red-200 hover:bg-red-800">
          Видалити
        </button>
        <a href="{% url 'projects:detail' project.pk %}" class="inline-flex items-center px-5 py-2.5 mt-4 text-sm font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:bg-blue-800">
          Назад
        </a>
      </form>
    </div>
  </section>
{% endblock content %}

src/templates/projects/project_detail.html
{% extends "base.html" %}

{% block title %}
  {{ project.title }}
{% endblock %}

{% block content %}
  <section class="mx-auto max-w-4xl mb-16">
    <div class="border border-gray-100 p-4 mb-4">
      <div class="flex items-center">
        <h1 class="flex-1 text-xl font-semibold mb-2 text-green-600">{{ project.title }}</h1>
        <span class="text-xl text-green-600">Бюджет: {{ project.price }} ₴</span>
      </div>

      <div class="flex mb-2 items-center">
        <div class="flex-1">
          <a href="{% url 'projects:list' %}?category_id={{ project.category.pk }}" class="text-gray-500 hover:underline">
            {{ project.category }}
          </a>
        </div>
        {% if project.is_higher_price_allowed %}
          <div class="text-gray-500">
            Макс. бюджет: {{ project.max_price }} ₴
          </div>
        {% endif %}
      </div>

      {% if messages %}
        {% for message in messages %}
          {% if message.extra_tags == 'warning' %}
            {% include "alert.html" with message=message style="warning" %}
          {% else %}
            {% include "alert.html" with message=message style="success" %}
          {% endif %}
        {% endfor %}
      {% endif %}

      <p class="mb-4">
        {{ project.description|linebreaksbr }}
      </p>

      <!-- MARK: О покупателе -->
      <div class="flex mb-2">
        <a href="{% url 'users:public_profile' project.customer.username %}">
          {% if project.customer.profile_image %}
            <img src="{{ project.customer.profile_image.url }}" class="h-16 w-16 mx-1" alt="{{ project.customer.username }}">
          {% else %}
            <div class="h-16 w-16 mx-1 bg-gray-200"></div>
          {% endif %}
        </a>
        <div class="flex flex-col px-2">
          <span>Покупатель: <a href="{% url 'users:public_profile' project.customer.username %}" class="hover:underline">{{ project.customer.username }}</a></span>
          <span>Размещено проєктов на бирже: {{ project.customer.projects.count }}</span>
        </div>
      </div>

      <!-- Кол-во откликов / кнопки -->
      <div class="flex items-center">
        <div class="flex-1 text-sm text-gray-500 font-thin">
          Переглядов: {{ total_views }} &middot; Предложений: {{ project.offers.count }}{# Тут будут все предложения, включая уже отклоненные. #}
        </div>
        <div>
          {% if user == project.customer and not order %}
            <!-- Кнопки для управления проєктом -->
            <a href="{% url 'projects:update' project.pk %}" class="inline-flex items-center px-5 py-2.5 text-sm font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:bg-blue-800">Змінити</a>
            <a href="{% url 'projects:delete' project.pk %}" class="inline-flex items-center px-5 py-2.5 text-sm font-medium text-center text-white bg-red-700 rounded-lg focus:ring-4 focus:ring-red-200 hover:bg-red-800">Видалити</a>
          {% else %}
            <!-- Кнопка подачи заявки -->
            {% if not offers.count and not order %}
              <form action="{% url 'projects:offer_create' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="project_id" value="{{ project.pk }}">
                <button class="mb-1 w-full text-white bg-green-600 hover:bg-green-700 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Предложить услугу</button>
              </form>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>

    {% if order %}
      <!-- MARK: Инфо о замовленняе на проєкт (видно только замовнику и исполнителю) -->
      <div class="border border-gray-100 p-4 mb-4">
        <div class="flex items-center">
          <div class="flex-1">
            <span class="text-xl">{{ order }}</span> <span class="text-gray-500">&middot; {{ order.get_status_display }}</span>
          </div>
          <div>
            <a href="{% url 'orders:detail' order.pk %}" class="mb-1 w-full text-white bg-green-600 hover:bg-green-700 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Перейти к замовленняу</a>
          </div>
        </div>
      </div>
    {% endif %}

    {% if offers.count %}
      <!-- MARK: Предложения по проєкту -->
      <div class="border border-gray-100 p-4 mb-4">
        {% if user == project.customer %}
          {# Для замовника проєкта показываем все предложения #}
          <h1 class="text-xl font-semibold mb-2">Предложения исполнителей</h1>
          
          {% if user.balance < project.price and project.is_active %}
            {% include "alert.html" with message="На вашому балансі недостатньо коштів, чтобы принять заявку на выполнение проєкта." style="warning" %}
          {% endif %}

          <div class="flex flex-col">
            {% for offer in offers %}
              <div class="flex p-2 mb-2 bg-gray-100">
                <!-- Аватарка -->
                {% if offer.candidate.profile_image %}
                  <a href="{% url 'users:public_profile' offer.candidate.username %}">
                    <img src="{{ offer.candidate.profile_image.url }}" class="h-16 w-16 mx-1 rounded-full" alt="{{ offer.candidate.username }}">
                  </a>
                {% else %}
                  <span class="h-16 w-16 mx-1 bg-gray-200 rounded-full"></span>
                {% endif %}
                <!-- Инфо -->
                <div class="flex items-center px-2 flex-1">
                  <div class="flex flex-col flex-1">
                    <span>
                      <a href="{% url 'users:public_profile' offer.candidate.username %}" class="hover:underline">
                        {{ offer.candidate.username }}
                      </a>
                    </span>
                    <span class="text-gray-500">
                      Создано {{ offer.created }}
                    </span>
                  </div>
                  <!-- Кнопки / инфо об отмене -->
                  <div class="flex">
                    {% if offer.is_cancelled or offer.status == 'accepted' %}
                      <span class="text-sm text-gray-500">{{ offer.get_status_display }}</span>
                    {% else %}
                      <!-- Кнопка "Принять" замовником -->
                      <form action="{% url 'projects:offer_set_status' offer.pk %}" method="POST" class="mr-1">
                        {% csrf_token %}
                        <input type="hidden" name="new_status" value="accepted">
                        <button class="w-full text-white bg-green-600 hover:bg-green-700 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Принять</button>
                      </form>
                      <!-- Кнопка "Отклонить" замовником -->
                      <form action="{% url 'projects:offer_set_status' offer.pk %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="new_status" value="declined">
                        <button class="w-full text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Отклонить</button>
                      </form>
                    {% endif %}
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        {% else %}
          {# Для остальных пользователей показываем только их предложение #}
          {% if offers.count %}
            <div class="flex items-center">
              <div class="flex-1">
                <div>Вы разместили предложениe {{ offers.0.created }}.</div>
                <div>Статус: {{ offers.0.get_status_display }}.</div>
              </div>
              <!-- Кнопки управления предложением - если оно не скасованоо -->
              {% if offers.0.is_cancelled or offers.0.status == 'accepted' %}
                <span class="text-sm text-gray-500">{{ offers.0.get_status_display }}</span>
              {% else %}
                <div>
                  <form action="{% url 'projects:offer_set_status' offers.0.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="new_status" value="cancelled">
                    <button class="w-full text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Скасувати предложение</button>
                  </form>
                </div>
              {% endif %}
            </div>
          {% endif %}
        {% endif %}
      </div>
    {% endif %}
  </section>
{% endblock content %}

src/templates/projects/project_list.html
{% extends "base.html" %}

{% block title %}
  Біржа проєктов
{% endblock %}

{% block content %}
  <section class="mx-auto max-w-6xl">
    {% if search %}
      <h1 class="text-2xl font-semibold mb-8">Пошук проєктов по запросу &laquo;{{ search }}&raquo;</h1>
    {% else %}
      {% if category %}
        <div class="text-gray-500 mb-4">{{ category }}</div>
        <h1 class="text-2xl font-semibold mb-8">{{ category.title }}</h1>
      {% else %}
        <h1 class="text-2xl font-semibold mb-8">Біржа проєктов</h1>
      {% endif %}
    {% endif %}

    <div class="text-gray-500 mb-4">{{ project_list.count }} результатов</div>
    <div class="grid grid-cols-12 gap-5">
      <!-- Left column 1/3 - filters -->
      <div class="col-span-3 flex flex-col">
        <div class="p-4 bg-gray-100 rounded-md shadow-md">
          <h2 class="text-xl font-medium mb-2">Рубрики</h2>
          <ul>
            <li><a href="{% url 'projects:list' %}" class="hover:underline">Усі</a></li>
            {% for cat in categories %}
              <li><a href="{% url 'projects:list' %}?category_id={{ cat.pk }}" class="hover:underline">{{ cat.title }}</a> <span class="text-gray-500">({{ cat.project_count }})</span></li>
            {% endfor %}
          </ul>
        </div>
      </div>

      <!-- Right column 3/4 - projects -->
      <div class="col-span-9">
        <!-- MARK: Строка поиска  -->
        {% include "search_form.html" with search=search %}

        {% if project_list.count %}
          <div class="flex flex-col">
            {% for project in project_list %}
              <!-- MARK: Карточка проєкта -->
              <div class="flex flex-col p-4 mb-4 border border-gray-100 hover:shadow-md rounded-lg">
                <div class="flex mb-1">
                  <a class="flex-1 text-xl font-medium hover:underline" href="{% url 'projects:detail' project.pk %}">{{ project.title }}</a>
                  <div class="text-xl text-green-500">{{ project.price }} ₴</div>
                </div>
                {% if not category %}
                  <a class="text-gray-500 mb-2 hover:underline" href="{% url 'projects:list' %}?category_id={{ project.category.pk }}">{{ project.category }}</a>
                {% endif %}
                <div class="flex">
                  <a href="{% url 'users:public_profile' project.customer.username %}">
                    {% if project.customer.profile_image %}
                      <img src="{{ project.customer.profile_image.url }}" class="h-16 w-16" alt="{{ project.customer.username }}">
                    {% else %}
                      <div class="h-16 w-16 mx-1 bg-gray-200"></div>
                    {% endif %}
                  </a>
                  <div class="flex flex-col px-2">
                    <span>Покупатель: <a href="{% url 'users:public_profile' project.customer.username %}" class="hover:underline">{{ project.customer.username }}</a></span>
                    <span>Размещено проєктов на бирже: {{ project.customer.projects.count }}</span>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        {% else %}
          {% include "alert.html" with message="Не найдено ни одной послуги, удовлетворяющей запросу. Попробуйте изменить фильтры, или выбрать другую рубрику." style="info" %}
        {% endif %}
      </div>
    </div>
  </section>
{% endblock content %}

src/templates/projects/project_my_list.html
{% extends "base.html" %}

{% block title %}
  Мої проєкти
{% endblock %}

{% block content %}
  <section class="mx-auto max-w-5xl">
    <div class="flex items-center mb-4">
      <h1 class="text-2xl font-semibold flex-1">Мої проєкти</h1>
      <a class="inline-flex items-center px-5 py-2.5 text-sm font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:bg-blue-800" href="{% url 'projects:create' %}">Створити проєкт</a>
    </div>

    <div>
      {% if not project_list.count %}
        {% include "alert.html" with message="Вы пока не разместили на сайти ни одного проєкта." style="info" %}
      {% endif %}

      {% for project in project_list %}
        <div class="p-4 border border-gray-100 mb-2 shadow-md">
          <div class="flex mb-2 items-center">
            <div class="flex-1">
              <a href="{% url 'projects:detail' project.pk %}" class="text-xl font-medium hover:underline">{{ project.title }}</a>
            </div>
            <div class="text-xl text-green-600">
              {{ project.price }} ₴
            </div>
          </div>
          <div class="mb-1">
            <a href="{% url 'projects:list' %}?category_id={{ project.category.pk }}" class="text-gray-500 hover:underline">
              {{ project.category }}
            </a>
          </div>
          <div>
            {% if project.offer_count %}<span class="text-green-600">Активных предложений: {{ project.offer_count }}</span>{% endif %}
          </div>
        </div>
      {% endfor %}
    </div>
  </section>
{% endblock content %}